---
title: "Exam 3"
author: "Kai Pauole"
date: "2026-04-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading and cleaing Faculty Salaries
```{r}
#loading packages
library(tidyverse)
library(ggplot2)
library(broom)
# loading and visulazing data
salaries = read.csv("C:/Users/kaipa/Downloads/Data_Course_PAUOLE/Exam/Exam_3/FacultySalaries_1995.csv")
str(salaries)
head(salaries)
# cleaning
cleaned_salaries = salaries %>% 
  pivot_longer(cols = c('AvgFullProfSalary', 'AvgAssocProfSalary', 'AvgAssistProfSalary'),
               names_to = 'Rank',
               values_to = 'Salary') %>% 
  mutate(Rank = recode(Rank,
                       'AvgFullProfSalary' = 'Full',
                       'AvgAssocProfSalary' = 'Assoc',
                       'AvgAssistProfSalary' = 'Assist'))
```
## Salary plot

```{r}
# salary plot
ggplot(cleaned_salaries %>% dplyr::filter(Tier %in% c("I", "IIA", "IIB")),
       aes(x = Rank, y = Salary, fill = Rank)) +
  geom_boxplot() +
  facet_wrap(~ Tier) +
  theme_minimal()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```
## ANOVA test
```{r}
# anova test
anova = aov(Salary ~ State + Tier + Rank, data = cleaned_salaries)

summary(anova)
```

## Juniper Data
```{r}
# loading in the data
Juniper = read.csv("C:/Users/kaipa/Downloads/Data_Course_PAUOLE/Exam/Exam_3/Juniper_Oils.csv")
```

Now tidy time
```{r}
# all chemicals 
Juniper_chemicals = c("alpha.pinene","para.cymene","alpha.terpineol","cedr.9.ene","alpha.cedrene","beta.cedrene","cis.thujopsene","alpha.himachalene","beta.chamigrene","cuparene","compound.1","alpha.chamigrene","widdrol","cedrol","beta.acorenol","alpha.acorenol","gamma.eudesmol","beta.eudesmol","alpha.eudesmol","cedr.8.en.13.ol","cedr.8.en.15.ol","compound.2","thujopsenal")

Juniper_cleaned = Juniper %>% 
  pivot_longer(cols = all_of(Juniper_chemicals),
               names_to = 'ChemicalID',
               values_to = 'Concentration')
```
The chemicals provided from the exam guide had '-' where as the actual data has '.' so I adjueted a little

Making the plot
```{r}
ggplot(Juniper_cleaned, aes(x = YearsSinceBurn, y = Concentration)) +
  geom_smooth() +
  facet_wrap(~ ChemicalID, scales = "free_y") +
  theme_minimal()
```

## Statistical Signiciance
```{r}
mod <- Juniper_cleaned %>%
  group_by(ChemicalID) %>%
  nest() %>%
  mutate(model = map(data, ~ lm(Concentration ~ YearsSinceBurn, data = Juniper_cleaned)))

Significance <- mod %>%
  mutate(tidy = map(model, tidy)) %>%
  unnest(tidy)

Significance
```



